name: terra_allwert_app
description: "Terra Allwert - A Flutter application with feature-first architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Firebase ---
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6
  firebase_performance: ^0.10.1

  # --- UI & Assets ---
  flutter_svg: ^2.1.0
  vector_graphics_compiler: ^1.1.17

  # --- Ads ---
  google_mobile_ads: ^6.0.0

  # --- App Updates ---
  force_update_helper: ^0.2.1

  # --- Logging ---
  talker: ^4.9.0

  # --- Configuration ---
  envied: ^1.1.1

  # --- URL Launcher ---
  url_launcher: ^6.3.1

  # --- Cache & Storage ---
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # --- Navigation ---
  go_router: ^15.1.3

  # --- HTTP & GraphQL ---
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  graphql_flutter: ^5.1.2
  
  # --- Database & Storage ---
  drift: ^2.20.1
  sqlite3_flutter_libs: ^0.5.27
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # --- MinIO & File Operations ---
  minio: ^3.0.11
  mime: ^1.0.6
  crypto: ^3.0.5
  
  # --- Images & Cache ---
  cached_network_image: ^3.4.1
  image: ^4.2.0
  
  # --- Connectivity ---
  connectivity_plus: ^6.1.0

  # --- State Management ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.6.1

  # --- Code Generation ---
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # --- Internationalization ---
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- Testing ---
  mocktail: ^1.0.4

  # --- Code Generation ---
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.6
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  envied_generator: ^1.1.1
  drift_dev: ^2.20.3

  # --- Linting ---
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # Fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
