name: terra_allwert_app
description: "Terra Allwert - A Flutter application with feature-first architecture"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Firebase --- (Removido: não está sendo utilizado no projeto)
  # firebase_core: ^4.0.0            # Core do Firebase - necessário para analytics, crashlytics
  # firebase_analytics: ^12.0.0      # Analytics para métricas de uso - adicionar quando necessário
  # firebase_crashlytics: ^5.0.0     # Crash reporting - importante para produção
  # firebase_performance: ^0.11.0    # Monitoring de performance - útil para otimizações

  # --- UI & Assets ---
  flutter_svg: ^2.1.0 # Necessário: SVG icons e assets
  vector_graphics_compiler: ^1.1.17 # Necessário: compilation de SVGs
  skeletonizer: ^2.1.0+1 # Necessário: loading skeletons implementados

  # --- App Updates --- (Removido: não implementado)
  # force_update_helper: ^0.2.1     # Force update - útil para versões críticas

  # --- Logging ---
  talker: ^5.0.0 # Necessário: sistema de logging implementado

  # --- Configuration ---
  envied: ^1.1.1 # Necessário: environment configuration

  # --- URL Launcher ---
  url_launcher: ^6.3.1 # Necessário: pode ser usado em links externos

  # --- Cache & Storage ---
  get_storage: ^2.1.1 # Necessário: usado em cache_manager.dart
  flutter_secure_storage: ^9.2.4 # Necessário: armazenamento seguro de tokens/credentials
  shared_preferences: ^2.3.4 # Necessário: preferências do usuário

  # --- Navigation ---
  go_router: ^16.2.1 # Necessário: sistema de roteamento

  # --- HTTP & GraphQL ---
  dio: ^5.8.0+1 # Necessário: HTTP client para downloads e API calls
  dio_cache_interceptor: ^4.0.3 # Necessário: cache de requisições HTTP
  graphql: ^5.2.1 # Necessário: cliente GraphQL implementado

  # --- Database & Storage --- (Database removida: usando apenas cache local)
  # drift: ^2.20.1                  # Database ORM - não está sendo usado
  # sqlite3_flutter_libs: ^0.5.27   # SQLite - não está sendo usado
  path_provider: ^2.1.5 # Necessário: paths do sistema de arquivos
  path: ^1.9.1 # Necessário: manipulação de paths

  # --- MinIO & File Operations ---
  minio: ^3.0.11
  mime: ^2.0.0
  crypto: ^3.0.5
  archive: ^4.0.7

  # --- Images & Cache ---
  cached_network_image: ^3.4.1
  image: ^4.2.0
  image_picker: ^1.1.2

  # --- Video Player ---
  video_player: ^2.9.2

  # --- Background Downloads ---
  background_downloader: ^9.2.3

  # --- UUID ---
  uuid: ^4.5.1

  # --- Maps ---
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # --- Drag and Drop ---
  reorderable_grid_view: ^2.2.8

  # --- File Picker ---
  file_picker: ^10.3.2

  # --- Connectivity ---
  connectivity_plus: ^6.1.0

  # --- State Management ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.6.1

  # --- Code Generation ---
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # --- Internationalization ---
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Testing ---
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

  # --- Code Generation ---
  build_runner: ^2.5.4 # Necessário: build runner para code generation
  riverpod_generator: ^2.6.5 # Necessário: geração de providers Riverpod
  riverpod_lint: ^2.6.5 # Necessário: linting para Riverpod
  custom_lint: ^0.7.6 # Necessário: linting customizado (compatível com riverpod_lint)
  freezed: ^3.0.6 # Necessário: code generation para classes imutáveis
  json_serializable: ^6.9.5 # Necessário: serialização JSON
  envied_generator: ^1.1.1 # Necessário: geração de environment config
  # drift_dev: ^2.20.3              # Database development - removido (não usado)

  # --- Linting ---
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # Fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
